[package]
name = "s3-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.3"
aws-sdk-s3 = "0.28.0"
aws-types = "0.55.3"
bytes = "1.4.0"
config = { version = "0.13.3", default-features = false }
http-body-util = "0.1.0-rc.3"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
mime = "0.3.17"
mime_guess = "2.0.4"
pin-project-lite = "0.2.13"
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
aws-credential-types = "0.55.3"
pretty_assertions = "1.4.0"
test-case = "3.1.0"

[features]
test = []
