[tasks.localstack-setup]
command = "docker"
args = ["run", "--rm", "-it", "-d", "--name", "localstack", "-p", "4566:4566", "-e", "SERVICES=sts,s3", "localstack/localstack"]

[tasks.localstack-teardown]
command = "docker"
args = ["kill", "localstack"]

[tasks.create-bucket]
env = { AWS_SECRET_ACCESS_KEY = "dummy", AWS_DEFAULT_REGION = "us-east-1" }
script = [
    "AWS_ACCESS_KEY_ID='123456789012' aws --endpoint-url=http://localhost:4566 s3 mb s3://localhost",
    "AWS_ACCESS_KEY_ID='123456789012' aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://localhost",
    "AWS_ACCESS_KEY_ID='234567890123' aws --endpoint-url=http://localhost:4566 s3 mb s3://test1.localhost",
    "AWS_ACCESS_KEY_ID='234567890123' aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://test1.localhost",
]

[tasks.create-bucket.windows]
env = { AWS_SECRET_ACCESS_KEY = "dummy", AWS_DEFAULT_REGION = "us-east-1" }
script = [
    "set AWS_ACCESS_KEY_ID='123456789012'",
    "aws --endpoint-url=http://localhost:4566 s3 mb s3://localhost",
    "aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://localhost",
    "set AWS_ACCESS_KEY_ID='234567890123'",
    "aws --endpoint-url=http://localhost:4566 s3 mb s3://another-account-bucket",
    "aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://another-account-bucket",
]

[tasks.local-setup]
run_task = { name = [
    "localstack-setup",
    "create-bucket",
], fork = true }

[tasks.local-teardown]
run_task = { name = [
    "localstack-teardown",
], fork = true }

[tasks.unit-tests]
command = "cargo"
args = ["test", "--", "--test-threads=1"]

[tasks.llvm-cov-open]
command = "cargo"
install_crate = "cargo-llvm-cov"
args = ["llvm-cov", "--open", "test", "--", "--test-threads=1"]

[tasks.aarch64-build]
command = "cargo"
install_crate = "cargo-zigbuild"
args = ["zigbuild", "--target", "aarch64-unknown-linux-gnu", "--release"]

[tasks.x86_64-build]
command = "cargo"
install_crate = "cargo-zigbuild"
args = ["zigbuild", "--target", "x86_64-unknown-linux-gnu", "--release"]

[tasks.all-build]
run_task = { name = [
    "aarch64-build",
    "x86_64-build",
], fork = true }

[tasks.buildx-build]
script = [
    "docker buildx create --use --name mybuilder",
    "docker buildx build --progress plain --platform linux/arm64,linux/amd64 -t storage-gateway .",
]

[tasks.container-build]
run_task = { name = [
    "all-build",
    "buildx-build",
], fork = true }