[tasks.localstack-setup]
script = [
    "docker run --rm -it -d --name localstack -p 4566:4566 -e SERVICES=sts,s3 localstack/localstack",
    "sleep 5",
]

[tasks.localstack-teardown]
command = "docker"
args = ["kill", "localstack"]

[tasks.create-bucket]
env = { AWS_SECRET_ACCESS_KEY = "dummy", AWS_DEFAULT_REGION = "us-east-1" }
script = [
    "AWS_ACCESS_KEY_ID='012345678901' aws --endpoint-url=http://localhost:4566 s3 mb s3://foo.example.com",
    "AWS_ACCESS_KEY_ID='012345678901' aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://foo.example.com",
    "AWS_ACCESS_KEY_ID='012345678901' aws --endpoint-url=http://localhost:4566 s3 mb s3://bar.example.net",
    "AWS_ACCESS_KEY_ID='012345678901' aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://bar.example.net",
    "AWS_ACCESS_KEY_ID='123456789012' aws --endpoint-url=http://localhost:4566 s3 mb s3://foobar.example.com",
    "AWS_ACCESS_KEY_ID='123456789012' aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://foobar.example.com",
]

[tasks.create-bucket.windows]
env = { AWS_SECRET_ACCESS_KEY = "dummy", AWS_DEFAULT_REGION = "us-east-1" }
script = [
    "set AWS_ACCESS_KEY_ID='012345678901'",
    "aws --endpoint-url=http://localhost:4566 s3 mb s3://foo.example.com",
    "aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://foo.example.com",
    "aws --endpoint-url=http://localhost:4566 s3 mb s3://bar.example.net",
    "aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://bar.example.net",
    "set AWS_ACCESS_KEY_ID='123456789012'",
    "aws --endpoint-url=http://localhost:4566 s3 mb s3://foobar.example.com",
    "aws --endpoint-url=http://localhost:4566 s3 sync ./tests/data s3://foobar.example.com",
]

[tasks.local-setup]
run_task = { name = [
    "localstack-setup",
    "create-bucket",
], fork = true }

[tasks.local-teardown]
run_task = { name = [
    "localstack-teardown",
], fork = true }

[tasks.test-bin-build]
install_crate = "cargo-zigbuild"
script = [
    "cargo zigbuild --target ${CARGO_MAKE_RUST_TARGET_ARCH}-unknown-linux-musl --features __tests",
    "cp target/${CARGO_MAKE_RUST_TARGET_ARCH}-unknown-linux-musl/debug/storage-gateway target/debug/storage-gateway",
]

[tasks.test-container-build]
dependencies = ["test-bin-build"]
command = "docker"
args = ["build", "-t", "test-storage-gateway", "-f", "test.Dockerfile", "."]

[tasks.integration-test]
command = "cargo"
args = ["test", "--test", "integration_test"]

[tasks.local-integration-test]
run_task = { name = [
    "test-container-build",
    "local-setup",
    "integration-test",
], fork = true, cleanup_task = "local-teardown" }

[tasks.aarch64-build]
command = "cargo"
install_crate = "cargo-zigbuild"
args = ["zigbuild", "--target", "aarch64-unknown-linux-musl", "--release"]

[tasks.x86_64-build]
command = "cargo"
install_crate = "cargo-zigbuild"
args = ["zigbuild", "--target", "x86_64-unknown-linux-musl", "--release"]

[tasks.container-build]
dependencies = ["aarch64-build", "x86_64-build"]
script = [
    "docker buildx create --use --name builder",
    "docker buildx build --platform linux/arm64,linux/amd64 -t storage-gateway -f release.Dockerfile .",
    "docker buildx rm builder",
]