name: CD

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-zigbuild

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u takenoko-gohan --password-stdin

      - name: Build and push
        run: |
          cargo make container-build-and-push
