name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check clippy
        run: |
          cargo clippy --all-features --tests -- -D warnings
          cargo clippy -- -D warnings

  unit-test:
    runs-on: ubuntu-latest
    needs: pre
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test

      - name: Install Cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Run unit test
        run: cargo make unit-test

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    services:
      localstack:
        image: localstack/localstack:stable
        env:
          SERVICES: s3,sts
        ports:
          - "4566:4566"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test

      - name: Install Cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-zigbuild

      - name: Setup localstack
        run: cargo make create-bucket

      - name: Build test container
        run: cargo make test-container-build

      - name: Run integration test
        run: cargo make integration-test
